name: order_tracking
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  ably_flutter: ^1.2.22
  firebase_core: ^2.14.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.5.3
  google_sign_in: ^6.1.6
  github_sign_in_plus: ^0.0.2
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
 uses-material-design: true

 assets:
   - assets/images/

 fonts:
   - family: Inter
     fonts:
       - asset: assets/fonts/Inter-Bold.ttf
         weight: 700
       - asset: assets/fonts/Inter-Light.ttf
         weight: 300
       - asset: assets/fonts/Inter-Medium.ttf
         weight: 500
       - asset: assets/fonts/Inter-Regular.ttf
         weight: 400
       - asset: assets/fonts/Inter-SemiBold.ttf
         weight: 600