// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1JY6rkwVAAUbvdmaKGNri091W7nDYq0',
    appId: '1:496120101636:web:c755fabb63c3cba4826e51',
    messagingSenderId: '496120101636',
    projectId: 'order-tracking-d95df',
    authDomain: 'order-tracking-d95df.firebaseapp.com',
    storageBucket: 'order-tracking-d95df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUnLr-6ifd9cK_805RXtr0e00-i2sfA0',
    appId: '1:496120101636:android:d95f6095861bb96c826e51',
    messagingSenderId: '496120101636',
    projectId: 'order-tracking-d95df',
    storageBucket: 'order-tracking-d95df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nG7arf4YZZ6pqJVuMscpODYIn-em9Gk',
    appId: '1:496120101636:ios:df14538c902cf1fe826e51',
    messagingSenderId: '496120101636',
    projectId: 'order-tracking-d95df',
    storageBucket: 'order-tracking-d95df.appspot.com',
    iosBundleId: 'com.example.orderTracking',
  );
}
